import { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { options } from '@/lib/auth-options';

import { DataTable } from './_components/data-table';
import { columns } from './_components/columns';
import { Client } from '@/interfaces/client';

export const metadata: Metadata = {
	title: 'Clientes',
	description: 'Generated by create next app',
};

async function getClients(accessToken: string): Promise<Client[]> {
	const resp = await fetch(`${process.env.API_URL}/client`, {
		headers: {
			Authorization: `Bearer ${accessToken}`,
		},
	});

	const data = await resp.json();

	return data.clients;
}

const ClientPage = async () => {
	const session = await getServerSession(options);
	const clients = await getClients(session!.accessToken);

	return <DataTable columns={columns} data={clients} />;
};

export default ClientPage;
