import { Metadata } from 'next';
import { Client } from '@/interfaces/client';
import { getServerSession } from 'next-auth';
import { options } from '@/lib/auth-options';
import { DataTable } from './components/data-table';

export const metadata: Metadata = {
	title: 'Clientes',
	description: 'Generated by create next app',
};

async function getClients(accessToken: string): Promise<Client[]> {
	const resp = await fetch(`${process.env.API_URL}/client`, {
		headers: {
			Authorization: `Bearer ${accessToken}`,
		},
	});

	const data = await resp.json();

	return data.clients;
}

const Page = async () => {
	const session = await getServerSession(options);
	const clients = await getClients(session!.accessToken);
	return (
		<div>
			<DataTable data={clients} />
		</div>
	);
};

export default Page;
