import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from './provider';
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Municipalidad - San José',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<html lang='en' suppressHydrationWarning>
				<body className={inter.className}>
					<Suspense fallback={<Loading />}>
						<NextAuthProvider>{children}</NextAuthProvider>
					</Suspense>
				</body>
			</html>
		</>
	);
}
