import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import { AuthProvider } from '@/context/auth/auth-provider';
import { NextAuthProvider } from './provider';
import { Suspense } from 'react';
import Loading from './loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<html lang='en' suppressHydrationWarning>
				<body className={inter.className}>
					<Suspense fallback={<Loading />}>
						<NextAuthProvider>
							<AuthProvider>
								<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
									{children}
									<Toaster />
								</ThemeProvider>
							</AuthProvider>
						</NextAuthProvider>
					</Suspense>
				</body>
			</html>
		</>
	);
}
