import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Configuración',
	description: 'Generated by create next app',
};

const Page = () => {
	return <div>Settings</div>;
};

export default Page;
