import { User } from '@/interfaces/user';
import { DataTable } from './_components/data-table';
import { getServerSession } from 'next-auth';
import { options } from '@/lib/auth-options';
import { Metadata } from 'next';
import { columns } from './_components/columns';

export const metadata: Metadata = {
	title: 'Usuarios',
	description: 'Generated by create next app',
};

async function getUsers(accessToken: string): Promise<User[]> {
	const resp = await fetch(`${process.env.API_URL}/user`, {
		headers: {
			Authorization: `Bearer ${accessToken}`,
		},
	});

	const data = await resp.json();

	return data.users;
}

export default async function Page() {
	const session = await getServerSession(options);
	const users = await getUsers(session!.accessToken);

	return <DataTable columns={columns} data={users} />;
}
