import { Metadata } from 'next';
import Main from './_components/main';
export const metadata: Metadata = {
	title: 'Reportes',
	description: 'Generated by create next app',
};

const Page = () => {
	return <div>
		<Main></Main>
	</div>;
};
export default Page;
