import { Metadata } from 'next';
import Main from './_components/main';
import { axios } from "@/lib/axios";
export const metadata: Metadata = {
	title: 'Reportes',
	description: 'Generated by create next app',
};

async function getYears(): Promise<any> {
   const data = await axios.get(`/reports/years`);
   return data.data
}


const Page = async () => {
	const data = await getYears()
	return (
    <div>
      <Main years={data.years} months={data.months}></Main>
    </div>
  );
};
export default Page;
